hunav_loader:
  ros__parameters:
    yaml_base_name: agents_factory
    simulator: Webots
    map: factory
    publish_people: true
    global_goals:
      1:
        x: 4.980
        y: -0.640
      2:
        x: 6.100
        y: -5.040
      3:
        x: 5.780
        y: -8.250
      4:
        x: -6.590
        y: -3.750
      5:
        x: -6.450
        y: -6.810
      6:
        x: -3.810
        y: -8.100
      7:
        x: 2.100
        y: -7.330
      8:
        x: 7.110
        y: -4.910
      9:
        x: 3.300
        y: -0.820
      10:
        x: -7.850
        y: -6.000
      11:
        x: -5.920
        y: -9.130
      12:
        x: -0.500
        y: -8.560
    agents:
      - agent1
      - agent2
      - agent3
      - agent4
    agent1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 1.5
      radius: 0.5
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: 1.50
        y: 0.00
        z: 0.01
        h: 0.0
      behavior:
        type: Regular
        configuration: 1
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 28.0
        other_force_factor: 20.0
      goals:
        - 1
        - 2
        - 3
    agent2:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 1.5
      radius: 0.5
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -6.16
        y: 0.11
        z: 0.01
        h: 0.0
      behavior:
        type: Threatening
        configuration: 1
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 28.0
        other_force_factor: 20.0
      goals:
        - 4
        - 5
        - 6
    agent3:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 1.5
      radius: 0.5
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -2.05
        y: -8.71
        z: 0.01
        h: 0.0
      behavior:
        type: Surprised
        configuration: 1
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 28.0
        other_force_factor: 20.0
      goals:
        - 7
        - 8
        - 9
    agent4:
      id: 4
      group_id: 4
      skin: 3
      max_vel: 1.5
      radius: 0.4
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -6.000
        y: -1.680
        z: 0.010
        h: 0.000
      behavior:
        type: Regular
        configuration: 1
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 28.0
        other_force_factor: 20.0
      goals:
        - 10
        - 11
        - 12