hunav_loader:
  ros__parameters:
    yaml_base_name: agents_office
    simulator: Webots
    map: office
    publish_people: true
    global_goals:
      1:
        x: 1.253
        y: -4.125
      2:
        x: -0.63
        y: -1.50
      3:
        x: -3.59
        y: -1.14
      4:
        x: -1.84
        y: 3.14
      5:
        x: -1.55
        y: -0.02
      6:
        x: -1.72
        y: -1.42

    agents:
      - agent1
      - agent2
    
    agent1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 1.5
      radius: 0.5
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -0.60937
        y: -5.00
        z: 0.01
        h: 1.250000
      behavior: 
        type: Regular # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 1 # def: 0, custom:1, random_normal:2, random_uniform:3
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 28.0
        other_force_factor: 20.0
      goals:
        - 1
        - 2
        - 3
      
    
    agent2:
        id: 2
        group_id: -1
        skin: 1
        max_vel: 1.5
        radius: 0.5
        goal_radius: 0.3
        cyclic_goals: true
        init_pose:
          x: -3.62
          y: 5.11
          z: 0.01
          h: 1.48
        behavior: 
          type: Regular # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
          configuration: 1   # def: 0, custom:1, random_normal:2, random_uniform:3
          goal_force_factor: 2.0
          obstacle_force_factor: 10.0
          social_force_factor: 28.0
          other_force_factor: 15.0
        goals:
          - 4
          - 5
          - 6
        