hunav_loader:
  ros__parameters:
    yaml_base_name: agents_office
    simulator: Webots
    map: office
    publish_people: true
    global_goals:
      1:
        x: 1.253
        y: -4.125
      2:
        x: -0.630
        y: -1.500
      3:
        x: -3.590
        y: -1.140
      4:
        x: -1.840
        y: 3.140
      5:
        x: -1.550
        y: -0.020
      6:
        x: -1.720
        y: -1.420
    agents:
      - agent1
      - agent2
    agent1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 1.5
      radius: 0.5
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -0.60937
        y: -5.00
        z: 0.01
        h: 1.250000
      behavior:
        type: Regular
        configuration: 1
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 28.0
        other_force_factor: 20.0
      goals:
        - 1
        - 2
        - 3
    agent2:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 1.5
      radius: 0.5
      goal_radius: 0.3
      cyclic_goals: true
      init_pose:
        x: -3.62
        y: 5.11
        z: 0.01
        h: 1.48
      behavior:
        type: Regular
        configuration: 1
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 28.0
        other_force_factor: 15.0
      goals:
        - 4
        - 5
        - 6